[tool.poetry]
<<<<<<< HEAD
name = "desafio-pida"
version = "0.1.0"
description = ""
authors = ["JersonPQ <prendes.2507@gmail.com>"]
=======
name = "transparencia-patrimonial"
version = "0.1.0"
description = ""
authors = ["samuel valverde <savalverde@estudiantec.cr>"]
>>>>>>> juli
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
<<<<<<< HEAD
numpy = "^2.3.4"
pandas = "^2.3.3"
geopandas = "^1.1.1"
matplotlib = "^3.10.7"
seaborn = "^0.13.2"
=======
streamlit = "^1.51.0"
pandas = "^2.3.3"
plotly = "^6.3.1"
joblib = "^1.5.2"
>>>>>>> juli
scikit-learn = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
